name: marinepred
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy==1.24.3
  - scipy
  - scikit-learn
  - pytorch::pytorch=2.12.1
  - pytorch::pytorch-cuda=12.1
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda-nvcc
  - cuda-toolkit::cuda-toolkit=12.1
  - cudnn
  - pip:
    - pandas==2.1.0
    - matplotlib==3.8.4
    - scikit-learn==1.3.1
    - tensorflow-intel==2.13.1
    - streamlit==1.28.0
    - plotly==5.17.0
    - pyyaml==6.0
    - tqdm==4.66.1
    - tensorboard==2.13.0
    - torch-geometric==2.4.0
